### ISSUE TITLE
just reports "JavaScript alerts." "Errors: undefined"  and "Connection terminated"

### ISSUE THREAD

**Issue by yarikoptic** [ancane/markdown-preview-mode#1]
websockets -- 1.4 straight from git , loaded directly via load-library.  The same way loaded markdown-preview-mode.  Base system -- Debian jessie, emacs 
24.4.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.5)

Results in a window simply with "Markdown preview" text in it

and 

```
WebSocket connection to 'ws://localhost:7379/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

Code: 1006 reason: 
```

sorry if it is just a user issue ;)
in console

**Comment by yarikoptic** [comment]
dunno -- did another restart and it started to work!! :-) thanks :+1:

**Comment by ancane** [comment]
haha. Please, tell me if it happens again.

**Comment by yarikoptic** [comment]
So far I can only say once again "THANK YOU" -- as long as it works, it seems the ultimate preview I was looking for!!! Thanks!

**Comment by yarikoptic** [comment]
btw -- how to switch to "GFM" mode (gfm-mode) provided by markdown-mode.el?  I guess there should be gfm-mode-preview ?
- may be you know, even with gfm-mode -- it doesn't provide GFM tables rendering, right?

**Comment by ancane** [comment]
Tables are not rendered by default `markdown` renderer, which is specified in `markdown-command` variable, which is customizable. You'd have to install markdown renderer for your OS that supports extended MD formatting, smth like this one http://fletcherpenney.net/multimarkdown/ and customize `markdown-command` like described here https://github.com/ancane/markdown-preview-mode#multimarkdown.
gfm-mode is probably enabled via just `gfm-mode` command ;)

**Comment by yarikoptic** [comment]
Thanks for the references!  I will check them out

> gfm-mode is probably enabled via just gfm-mode command ;)

indeed -- but it disables markdown-preview-mode (no updates get rendered etc)

**Comment by ancane** [comment]
Thanks for pointing this out. :+1: I'll have a look.

**Comment by yarikoptic** [comment]
FWIW -- thanks for the multimarkdown reference -- works beautifully... if only I had time I would have taken to package it up for Debian (RFP is open https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=659343)

**Comment by ancane** [comment]
Working in gfm-mode should be better now.

> but it disables markdown-preview-mode (no updates get rendered etc)

gfm-mode, just like markdown-mode, is a major mode. When you switch between major modes, minor mode like `markdown-preview-mode` is disabled and you have to enable it back.
Minor mode can be automatically enabled by registering a major mode hook, like this:
`(add-hook 'markdown-mode-hook (lambda () ( markdown-preview-mode 1 ) ))`
`(add-hook 'gfm-mode-hook (lambda () ( markdown-preview-mode 1 ) ))`
