### ISSUE TITLE
Listen on localhost by default

### ISSUE THREAD

**Issue by chwarr** [ancane/markdown-preview-mode#10]
In commit ahyatt/emacs-websocket@19f9b3b74f1dd980fb2d24c16816755f2428ba06, support was added to the websocket package to specify the host to listen on.

I think it would be good to build atop this functionality and have markdown-preview-mode listen only on localhost by default (with customization to support alternatives).

Is this a feature that would make sense? (I have it coded up and tested against websocket HEAD, but wanted to start with an issue instead of a PR.)

And, anyway, we'd need to wait for a new version of websocket to be published to consume this in stable.

**Comment by ancane** [comment]
Thank you @chwarr. Configurable server address makes perfect sence to me.

**Comment by chwarr** [comment]
Thanks. A [bit different from what I had](https://github.com/chwarr/markdown-preview-mode/commit/f1511082258e0744cc432ea172e6bd2988fa3e0a), but not in important ways. :-)

**Comment by ancane** [comment]
@chwarr Somehow I've missed your code, sorry. Could you, please, PR you defcustom? Adding `0.0.0.0` as an explicit const whould be perfect. And I'm adding 'hardcoded localhost' issue. Thank you.

**Comment by chwarr** [comment]
This is a FSF project, right? If so, I don't think I'll be able to contribute this code back to the mainline repository for markdown-preview-mode. I am not currently able to complete the FSF copyright assignment process to the satisfaction of the FSF, and most FSF projects need to hold the copyright over all the contributions.

If you can accept a contribution that remains my work (still under the GPLv3 and all that) or if this contribution is small enough to not need copyright assignment, I'm happy to start a PR.

**Comment by ancane** [comment]
Correct, but the change is small and we can skip the assignment.
