### ISSUE TITLE
Relative path for links

### ISSUE THREAD

**Issue by nickjmeyer** [ancane/markdown-preview-mode#11]
I'm trying to embed an SVG into my markdown.  I have it set as a relative path
`![Some image](../some_image.svg)`
But, since the server is watching a temporary file in a different directory it loads a broken link.

How can I get the markdown-preview-mode to embed images with relative paths?

**Comment by ancane** [comment]
Hi. Unfortunately, there is no sane support for relative paths yet. But as a workaround, I open my dev console and see `GET file:///home/igorsh/.emacs.d/el-get/markdown-preview-mode/some_image.svg net::ERR_FILE_NOT_FOUND` error. Then I put `some_image.svg` into `file:///home/igorsh/.emacs.d/el-get/markdown-preview-mode/` and ... voila :)

**Comment by MikeWallaceDev** [comment]
As a workaround, I created a symbolic link from ~.emacs.d/el-get/markdown-preview-mode/  to the directory where my graphics are.  It worked.

Thanks for your work @ancane

**Comment by nickjmeyer** [comment]
Awesome, thanks!  P.S.  I really like this mode.  Makes editing md files much more enjoyable.

Also been nice for group meetings.  I put the browser on the projector and everyone can see the rendered md file.

**Comment by jeanbaptistelab** [comment]
Hi,

I had a similar need (allow links to files/images relative to the previewed Markdown file), and came up with something that works for me...
I created PR #13 but I'm no elisp expert so the code may not meet your standards. Anyway, this does the trick for me and maybe useful to others...

Thanks,

JB

**Comment by ancane** [comment]
@jeanbaptistelab Thanks a lot for this contrib. Looks good, works great :+1:

**Comment by jeanbaptistelab** [comment]
@ancane no problem, it was (well to me anyway) a nice isolated issue to work on. Error handling is missing though and clean up of the temp preview file needs to be done too, but as a first stab, it works OK.
Thanks!

**Comment by ancane** [comment]
v0.5 released with relative links support. Thank you all.
