### ISSUE TITLE
Update on idle stops working after a couple of minutes

### ISSUE THREAD

**Issue by pmcnr-hx** [ancane/markdown-preview-mode#12]
I'm really enjoying using `markdown-preview-mode` and it does its job very well. Thanks for this excellent project.

Unfortunately, update on idle (which I find really useful), seems to stop working after a couple of minutes. Any ideas what might be causing this issue?

**Comment by ancane** [comment]
Thank you @pmcnr-hx. Probably, I've overlooked some crucial part regarding idle timers. I'll take another look.

**Comment by ancane** [comment]
@pmcnr-hx Idle should work fine in v0.4. I misused `kill-buffer-hook`.

**Comment by pmcnr-hx** [comment]
Brilliant. Thank you very much for such a prompt fix @ancane!
