### ISSUE TITLE
Hardcoded Stylesheet in .markdown-preview.html

### ISSUE THREAD

**Issue by vanderheijden86** [ancane/markdown-preview-mode#15]
Altough I change the style sheet by customizing markdown-preview-style, I still am not able to get the right stylesheet connected in the preview. I check this out and in the .html file the link to the standard thomasf.github stylesheet is present. Can you help me out? Thanks a lot.

**Comment by ancane** [comment]
Hey. Strange but customizing style var works on my machine. Lets see. Stylesheet file is coded into `-preview.html` file for sake of default css for the page only. It is replaced by the style var after page is connected to emacs buffer. So, here are 2 options possible: javascipt error seen in browser console, which prevents from replacing stylesheet tag, or it's variable to blame, meaning new value didn't apply. If you find nothing strange in the browser console, then please check the output of `M-x describe-variable RET markdown-preview-style RET`.

**Comment by vanderheijden86** [comment]
Hi, thanks for the fast reply. No browser erros, it's value is:

markdown-preview-style is a variable defined in `markdown-preview-mode.el'.
Its value is
"https://sindresorhus.com/github-markdown-css/github-markdown.css"

**Comment by vanderheijden86** [comment]
When I inspect with Chrome I see that the stylesheet value in the header is updated to reflect the correct link, however the actual styles are not applied to the elemens (h1, h2 etc). Strange...

**Comment by vanderheijden86** [comment]
Figured it out :-). When I change "<article id=", to "<article class=" it works. Apparently markdown changed from setting the id of the article to setting the class. 

<img width="1151" alt="screen shot 2016-09-23 at 11 20 36" src="https://cloud.githubusercontent.com/assets/16118904/18780874/cf7bb4a8-817f-11e6-9344-e1e1799bfefc.png">

**Comment by ancane** [comment]
I see. It's a github markdown css file. I guess, this css should be paired with appropriate markdown processor.

**Comment by vanderheijden86** [comment]
One quick question, do you know how I can pair the right processor? I can't find a markdown binary which does exactly render like github. Instead I use a command line utility named [grip](https://github.com/joeyespo/grip) now. Can I hook this up with markdown-preview-mode?

**Comment by ancane** [comment]
Sure. That's done via customizing `markdown-command` variable.

**Comment by ancane** [comment]
I guess, thanks to @zenkiezhu this can be closed now.
