### ISSUE TITLE
Question? Is remote live preview possible?

### ISSUE THREAD

**Issue by arronmabrey** [ancane/markdown-preview-mode#17]
It's nice that this package uses websockets to send the changes to the browser, most other packages only support reloading a file on disk.

I strictly use emacs over ssh, but still I'd like to preview the markdown in my local browser (the machine I'm typing on, not the remote machine running the emacs process).  I can easily proxy the web socket ports to my local box using.

``` bash
ssh -NL 0.0.0.0:7379:0.0.0.0:7379 my-box-with-emacs
```

That's awesome, but the sticking point right now is the initial html payload that loads the JS is using browse-url which doesn't work, it open the browser on the remote machine running emacs. 

Would it be possible to also server that "preview" file over http:// vs file://? If that was supported I'd be able to forward that second http port (say 8080) and open the preview on my local machine.

``` bash
ssh -NL 0.0.0.0:8080:0.0.0.0:8080 my-box-with-emacs
```

**Comment by ancane** [comment]
Hi @arronmabrey. My apologies for taking so long at this feature request. Thanks for great idea that made me rethink the preview. Now that preview is accessible via http it's possible to disable opening browser window on remote host and open multiple preview windows locally via same tunnel port. Hopefully it works fine. Cheers. [doc](https://github.com/ancane/markdown-preview-mode#remote-access)

**Comment by arronmabrey** [comment]
@ancane 🎉 🎉 Good Job!! 🎉 🎉 I've got it working, and it's pretty slick!

Thanks a bunch!

-- Arron
