### ISSUE TITLE
"make server process failed" when enabling markdown-preview-mode

### ISSUE THREAD

**Issue by diegov** [ancane/markdown-preview-mode#30]
Hi, 

I'm seeing this when I try to enable markdown-preview-mode

```
apply: make server process failed: Success, :name, ws-server, :service, 9000, :filter, ws-filter, :server, t, :nowait, t, :family, ipv4, :coding, no-conversion, :plist, (:server #s(#s(eieio--class ws-server nil nil [#s(cl-slot-descriptor handlers nil t nil) #s(cl-slot-descriptor process nil t nil) #s(cl-slot-descriptor port nil t nil) #s(cl-slot-descriptor requests nil t nil)] #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8125 data (handlers 0 process 1 port 2 requests 3 ...)) nil ((:handlers . handlers) (:process . process) (:port . port) (:requests . requests)) [] [] ...) (lambda (&rest --cl-rest--) (apply (function #[(G62 request) 	""AO
J"
6\0	"
r	"!"q)""f\0
J\0	"
""f\0!`\0!`\0	""f\0	"!+ [request object path G62 filename markdown-preview-file-name assoc :GET slot-value headers ...] 9]) (quote --docroot--) --cl-rest--)) nil 9000 nil)), :log, nil, :host, localhost
```

The browser window opens but no process is listening on port 9000.

I have the markdown command in the path, and the markdown-preview command opens the preview in the browser correctly. I tried changing the http and ws ports but that didn't help.

I'm running GNU Emacs 26.0.91, and markdown-preview-mode v. 20171121.2323.

Cheers
Diego

**Comment by diegov** [comment]
This seems very similar to https://github.com/yati-sagade/orch/issues/3. 
The web-server package hasn't been updated since 2014, maybe it's an issue between it and emacs 26?

**Comment by ancane** [comment]
Emacs 25.3 is still the latest release. I hope whatever is broken in 26.0 gets fixed when becomes officially released. If not, then I hope release note will give a clue on what's need to be fixed. I'd wait till 26 release if you don't mind.

**Comment by brandon-arnold** [comment]
Emacs 26 was released some weeks back and this issue remains. Probably want to think about a different method than `web-server` package.

**Comment by ancane** [comment]
@brandon-arnold Thx for notice. I'll try to dig into issue one more time.
