### ISSUE TITLE
Cannot open localhost:9000

### ISSUE THREAD

**Issue by chabashilah** [ancane/markdown-preview-mode#33]
Hi, I am using ArchLinux(4.17.11-arch1) and emacs 26.1.
When I open markdown-preview-mode, it automatically opens browser but it just says "This site cannot be reached".

Am I missing something to configure?
I confirmed 9000 port is not opened with lsof command.

**Comment by phipsgabler** [comment]
I'm experiencing the same thing in Ubuntu 18.04, Emacs 27.0.50.  The buffer `*markdown-output*` contains (only)
```
zsh:1: command not found: pandoc
```

although pandoc is there through conda:

```
╰❯ which pandoc
~/anaconda3/bin/pandoc
```

Can I provide any other information to help debug it?

**Comment by seagle0128** [comment]
Same issue here, on Linux Mint 19 with Emacs 26.1. I confirmed the firewall has been closed.

Error messages:
```elisp
Debugger entered--Lisp error: (file-error "make server process failed" "Success" :name "ws-server" :service 9000 :filter ws-filter :server t :nowait t :family ipv4 :coding no-conversion :plist (:server #<ws-server ws-server>) :log nil :host "localhost")
  make-network-process(:name "ws-server" :service 9000 :filter ws-filter :server t :nowait t :family ipv4 :coding no-conversion :plist (:server #<ws-server ws-server>) :log nil :host "localhost")
  apply(make-network-process :name "ws-server" :service 9000 :filter ws-filter :server t :nowait t :family ipv4 :coding no-conversion :plist (:server #<ws-server ws-server>) :log nil (:host "localhost"))
  ws-start((lambda (&rest --cl-rest--) (apply (function #f(compiled-function (G61 request) #<bytecode 0x11c3afd>)) '--docroot-- --cl-rest--)) 9000 nil :host "localhost")
  markdown-preview--start-http-server(9000)
  markdown-preview--start()
  markdown-preview-mode(toggle)
  funcall-interactively(markdown-preview-mode toggle)
  call-interactively(markdown-preview-mode nil nil)
  command-execute(markdown-preview-mode)
```

**Comment by juergenhoetzel** [comment]
> Same issue here, on Linux Mint 19 with Emacs 26.1. I confirmed the firewall has been closed.
> 
> Error messages:
> 
> ```emacs-lisp
> Debugger entered--Lisp error: (file-error "make server process failed" "Success" :name "ws-server" :service 9000 :filter ws-filter :server t :nowait t :family ipv4 :coding no-conversion :plist (:server #<ws-server ws-server>) :log nil :host "localhost")
>   make-network-process(:name "ws-server" :service 9000 :filter ws-filter :server t :nowait t :family ipv4 :coding no-conversion :plist (:server #<ws-server ws-server>) :log nil :host "localhost")
>   apply(make-network-process :name "ws-server" :service 9000 :filter ws-filter :server t :nowait t :family ipv4 :coding no-conversion :plist (:server #<ws-server ws-server>) :log nil (:host "localhost"))
>   ws-start((lambda (&rest --cl-rest--) (apply (function #f(compiled-function (G61 request) #<bytecode 0x11c3afd>)) '--docroot-- --cl-rest--)) 9000 nil :host "localhost")
>   markdown-preview--start-http-server(9000)
>   markdown-preview--start()
>   markdown-preview-mode(toggle)
>   funcall-interactively(markdown-preview-mode toggle)
>   call-interactively(markdown-preview-mode nil nil)
>   command-execute(markdown-preview-mode)
> ```

Upstream Bug:  https://github.com/eschulte/emacs-web-server/issues/10

**Comment by juergenhoetzel** [comment]
Added workaround for Emacs 26.1 async issues: #35
