### ISSUE TITLE
Byte-compiler warning that the function 'my-filter' is unknown

### ISSUE THREAD

**Issue by pierre-rouleau** [ancane/markdown-preview-mode#47]
Byte compilation of the latest version of the file gives a warning about the function ``my-filter`` not defined, as used in the ``advice-remove`` form in the last line of ``markdown-preview--start-http-server``.

Here's the byte compiler log:
```
Compiling file /Users/roup/.emacs.d/elpa/markdown-preview-mode-20210207.2114/markdown-preview-mode.el at Sat May 15 12:25:59 2021

In end of data:
markdown-preview-mode.el:419:1:Warning: the function ‘my-filter’ is not known
    to be defined.
```

**Comment by pierre-rouleau** [comment]
Is this line really needed?  I didn't see any mention of that function in the docs.  Is this forgotten cleanup?

**Comment by ancane** [comment]
@pierre-rouleau version 0.9.4 should fix that. Thank you for reporting.
