### ISSUE TITLE
Doesn't open browser

### ISSUE THREAD

**Issue by mattiasb** [ancane/markdown-preview-mode#7]
When starting `markdown-preview-mode` I don't get a preview in my browser. Not even when manually running `markdown-preview-open-browser`.

I checked that `browse-url-at-point` works (which uses `browse-url-browser-function`) and it does.

I use pandoc to generate markdown and this is the value of `markdown-command`:

```
pandoc -s -f markdown_github -c file:///home/mattiasb/.emacs.d/github-pandoc.css
```

might this be the cause?

**Comment by ancane** [comment]
Hi. Strange. I've just installed pandoc, modified markdown-command to match yours and it worked fine.
Did it brake after you customized `markdown-command` or preview did not work for you at all?

**Comment by mattiasb** [comment]
When I activated `markdown-preview-mode` nothing user visible happened (and nothing in _Messages_), and the same if I then run `markdown-preview-open-browser`.

I'll see if I can debug this in some way. It sounds like a bug in or at least a conflict with my config.

**Comment by ancane** [comment]
I'll try to debug it on your .emacs.d, tonigth.

**Comment by mattiasb** [comment]
Oh! You really don't need to, but thanks a lot! :D <3

EDIT: I'm using `control-mode` so if you're trying with my emacs.d you'll need to press `i` to get into input mode (similar to `evil`).

**Comment by ancane** [comment]
Okey. I've found the problem. `markdown-preview-mode` package is missing required file due to incorrectly defined recipe :( That's shame. Installing the mode via package.el doesn't really work at the moment.

**Comment by mattiasb** [comment]
Ah!

**Comment by mattiasb** [comment]
As a work around I did a manual copy of preview.html into the install folder of `markdown-preview-mode` and everything is working great! Thanks for your help!

**Comment by ancane** [comment]
@mattiasb It should work fine now, starting from v0.2.

**Comment by mattiasb** [comment]
@ancane great, thanks!
