### ISSUE TITLE
Problems with utf8 charset

### ISSUE THREAD

**Issue by 316k** [ancane/markdown-preview-mode#9]
I've got problems with utf8 characters, (e.g.: "é" is shown as "Ã©").

By the way, it's a pretty cool mode !

**Comment by ancane** [comment]
Good catch, thank you.

**Comment by ancane** [comment]
@316k Thanks again for reporting this. I've published fix for unicode characters under v0.3. It should become available soon at melpa. Could you, please, check if that works for you?

**Comment by 316k** [comment]
Works fine, thanks a lot ! :)
